# Generated by Django 3.1.2 on 2022-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.ImageField(upload_to='', verbose_name='FOTO')),
                ('release_date', models.CharField(max_length=11)),
                ('lte_exists', models.BooleanField(verbose_name='BOOL')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='URL')),
            ],
        ),
    ]
